---
- name: Create Security Group for ALB
  amazon.aws.ec2_security_group:
    name: "{{ alb_security_group_name }}"
    description: "Security group for the Application Load Balancer"
    vpc_id: "{{ vpc.vpc.id  }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: "0.0.0.0/0"
    rules_egress:
      - proto: -1
        cidr_ip: "0.0.0.0/0"
    state: present
  register: alb_security_group

- name: Debug ALB Security Group
  ansible.builtin.debug:
    var: alb_security_group

- name: Create Security Group for ECS
  amazon.aws.ec2_security_group:
    name: "{{ ecs_security_group_name }}"
    description: "Security group for the ECS service"
    vpc_id: "{{ vpc.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        group_id: "{{ alb_security_group.group_id }}"
    rules_egress:
      - proto: -1
        cidr_ip: "0.0.0.0/0"
    state: present
  register: ecs_security_group
